steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/app-engine-images', '--file', './Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/app-engine-images']
- name: "gcr.io/cloud-builders/gcloud"
  args: ['app', 'deploy', '--image-url=europe-west1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/app-engine-images:latest']
