# Generated by Django 4.2.1 on 2023-05-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_baseemployee_remove_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseemployee',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
