# Generated by Django 4.2.1 on 2023-05-23 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('baseemployee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.baseemployee')),
            ],
            bases=('accounts.baseemployee',),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('customer', 'Customer')], max_length=8),
        ),
    ]
